-- Bicolore BG: Funghi
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Marcio', 2, 'BG', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo del Varco', 2, 'BG', 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Velenoso', 2, 'BG', 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Parassita', 3, 'BG', 2, 3, 0, 0, 0, 0, 0, 0, 0, 1, 'uncommon', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Corruttore', 3, 'BG', 3, 2, 0, 0, 1, 0, 0, 0, 0, 0, 'common', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Putrefatto', 3, 'BG', 2, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Funghi', 3, 'BG', 3, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Gigante', 4, 'BG', 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo Mortale', 4, 'BG', 3, 5, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fungo della Corruzione', 4, 'BG', 5, 4, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Funghi', 5, 'BG', 5, 5, 0, 0, 1, 1, 0, 0, 0, 0, 'rare', 'Fungus', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Parassita Primordiale', 6, 'BG', 6, 6, 0, 0, 1, 1, 0, 0, 0, 0, 'mythic', 'Fungus', '', 1, 'custom');
