-- Bicolore BR: Berserker
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Feroce', 2, 'BR', 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 'common', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker del Varco', 2, 'BR', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Selvaggio', 2, 'BR', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Furibondo', 3, 'BR', 3, 2, 0, 1, 0, 1, 0, 0, 0, 0, 'uncommon', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Indomabile', 3, 'BR', 4, 2, 0, 1, 0, 1, 0, 0, 0, 0, 'common', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Tempestoso', 3, 'BR', 2, 3, 0, 0, 0, 1, 1, 0, 0, 0, 'uncommon', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Berserker', 3, 'BR', 3, 3, 0, 1, 0, 1, 1, 0, 0, 0, 'rare', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Titano', 4, 'BR', 5, 4, 0, 1, 0, 1, 1, 0, 0, 0, 'uncommon', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker Immortale', 4, 'BR', 4, 4, 0, 1, 0, 1, 1, 0, 0, 0, 'rare', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Berserker della Furia', 4, 'BR', 5, 5, 0, 1, 0, 1, 1, 0, 0, 0, 'rare', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Berserker', 5, 'BR', 5, 5, 0, 1, 0, 1, 1, 0, 0, 0, 'rare', 'Berserker', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sovrano della Furia Primordiale', 6, 'BR', 6, 6, 0, 1, 0, 1, 1, 0, 0, 0, 'mythic', 'Berserker', '', 1, 'custom');
