-- Carte verdi custom: Serpenti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente della Giungla', 2, 'G', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente del Varco', 2, 'G', 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 'common', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Velenoso', 2, 'G', 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Cacciatore', 3, 'G', 3, 2, 0, 0, 1, 0, 0, 0, 1, 0, 'uncommon', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Constrictor', 3, 'G', 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Mortale', 3, 'G', 2, 3, 0, 0, 1, 0, 0, 0, 1, 0, 'uncommon', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Serpenti', 3, 'G', 3, 3, 0, 0, 1, 0, 0, 0, 1, 0, 'rare', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Colossale', 4, 'G', 5, 4, 0, 0, 0, 1, 0, 0, 0, 0, 'uncommon', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente Primordiale', 4, 'G', 4, 5, 0, 0, 1, 0, 0, 0, 1, 0, 'rare', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Serpente della Morte', 4, 'G', 5, 4, 0, 0, 1, 0, 0, 0, 1, 0, 'rare', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Serpenti', 5, 'G', 5, 5, 0, 0, 1, 1, 0, 0, 1, 0, 'rare', 'Snake', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Basilisco Antico', 6, 'G', 6, 5, 0, 0, 1, 1, 0, 0, 1, 0, 'mythic', 'Snake', '', 1, 'custom');
