-- Bicolore GU: Mutanti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Marino', 2, 'GU', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante del Varco', 2, 'GU', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Creatura Mutante', 2, 'GU', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Acquatico', 3, 'GU', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mostro Mutante', 3, 'GU', 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Abominio Mutante', 3, 'GU', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Mutanti', 3, 'GU', 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Colossale', 4, 'GU', 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Primordiale', 4, 'GU', 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Aberrazione Mutante', 4, 'GU', 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Mutanti', 5, 'GU', 5, 5, 0, 0, 0, 1, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Evoluzione Primordiale', 6, 'GU', 6, 6, 0, 0, 0, 1, 0, 0, 0, 0, 'mythic', 'Mutant', '', 1, 'custom');
