-- Bicolore GW: Elefanti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Protettore', 2, 'GW', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante del Varco', 2, 'GW', 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Nobile', 2, 'GW', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Guaritore', 3, 'GW', 3, 3, 0, 0, 0, 1, 0, 1, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Saggio', 3, 'GW', 2, 4, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Potente', 3, 'GW', 3, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore degli Elefanti', 3, 'GW', 3, 4, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Colossale', 4, 'GW', 4, 5, 0, 0, 0, 1, 0, 1, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Antico', 4, 'GW', 5, 4, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Immortale', 4, 'GW', 4, 6, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re degli Elefanti', 5, 'GW', 5, 5, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Patriarca Elefante Eterno', 6, 'GW', 6, 7, 0, 0, 0, 1, 0, 1, 0, 0, 'mythic', 'Elephant', '', 1, 'custom');
