-- Multicolore cards: GW Elephants + GU Mutants + WU Sphinx
-- Esecuzione: dbx.php?file=multicolors.sql oppure mysql < sql/multicolors.sql

-- Bicolore GW: Elefanti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Protettore', 2, 'GW', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante del Varco', 2, 'GW', 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Nobile', 2, 'GW', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Guaritore', 3, 'GW', 3, 3, 0, 0, 0, 1, 0, 1, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Saggio', 3, 'GW', 2, 4, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Potente', 3, 'GW', 3, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore degli Elefanti', 3, 'GW', 3, 4, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Colossale', 4, 'GW', 4, 5, 0, 0, 0, 1, 0, 1, 0, 0, 'uncommon', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Antico', 4, 'GW', 5, 4, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Elefante Immortale', 4, 'GW', 4, 6, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re degli Elefanti', 5, 'GW', 5, 5, 0, 0, 0, 1, 0, 1, 0, 0, 'rare', 'Elephant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Patriarca Elefante Eterno', 6, 'GW', 6, 7, 0, 0, 0, 1, 0, 1, 0, 0, 'mythic', 'Elephant', '', 1, 'custom');

-- Bicolore GU: Mutanti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Marino', 2, 'GU', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante del Varco', 2, 'GU', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Creatura Mutante', 2, 'GU', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Acquatico', 3, 'GU', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mostro Mutante', 3, 'GU', 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Abominio Mutante', 3, 'GU', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Mutanti', 3, 'GU', 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Colossale', 4, 'GU', 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Mutante Primordiale', 4, 'GU', 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Aberrazione Mutante', 4, 'GU', 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Mutanti', 5, 'GU', 5, 5, 0, 0, 0, 1, 0, 0, 0, 0, 'rare', 'Mutant', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Evoluzione Primordiale', 6, 'GU', 6, 6, 0, 0, 0, 1, 0, 0, 0, 0, 'mythic', 'Mutant', '', 1, 'custom');

-- Bicolore WU: Sphinx
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Custode', 2, 'WU', 1, 3, 1, 0, 0, 0, 0, 0, 0, 1, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge del Varco', 2, 'WU', 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Saggio', 2, 'WU', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Sapiente', 3, 'WU', 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Consigliata', 3, 'WU', 2, 3, 1, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Guardiana', 3, 'WU', 1, 4, 1, 0, 0, 0, 0, 0, 1, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore degli Sphinx', 3, 'WU', 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Colossale', 4, 'WU', 4, 4, 1, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Primordiale', 4, 'WU', 4, 4, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Celeste', 4, 'WU', 3, 5, 1, 0, 0, 0, 0, 1, 1, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re degli Sphinx', 5, 'WU', 5, 5, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Eternale', 6, 'WU', 5, 6, 1, 0, 0, 0, 0, 1, 1, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Patriarca Sphinx Immortale', 6, 'WU', 6, 6, 1, 1, 0, 0, 0, 1, 0, 0, 'mythic', 'Sphinx', '', 1, 'custom');
