-- Carte rosse custom: Nani
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Minatore', 2, 'R', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano del Varco', 2, 'R', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Guerriero', 2, 'R', 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 'uncommon', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Asciatore', 3, 'R', 3, 2, 0, 1, 0, 0, 0, 0, 0, 0, 'uncommon', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Fabbro', 3, 'R', 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Bretone', 3, 'R', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Nani', 3, 'R', 3, 3, 0, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Regnante', 4, 'R', 4, 3, 0, 1, 0, 0, 0, 0, 0, 0, 'uncommon', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano della Montagna', 4, 'R', 3, 4, 0, 0, 0, 0, 0, 0, 0, 1, 'rare', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Nano Guerriero Antico', 4, 'R', 4, 4, 0, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Nani', 5, 'R', 5, 4, 0, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Dwarf', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore della Montagna di Ferro', 6, 'R', 6, 5, 0, 1, 0, 0, 0, 0, 0, 0, 'mythic', 'Dwarf', '', 1, 'custom');
