-- Bicolore RG: Bestie Selvaggi
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Selvaggia', 2, 'RG', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia del Varco', 2, 'RG', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Predatore Selvaggio', 2, 'RG', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Furiosa', 3, 'RG', 3, 2, 0, 1, 0, 1, 0, 0, 0, 0, 'uncommon', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Indomita', 3, 'RG', 3, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'common', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Sanguinaria', 3, 'RG', 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 'uncommon', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore delle Bestie Selvagge', 3, 'RG', 3, 3, 0, 1, 0, 1, 0, 0, 0, 0, 'rare', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Titano Selvaggio', 4, 'RG', 4, 4, 0, 1, 0, 1, 0, 0, 0, 0, 'uncommon', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Primitiva', 4, 'RG', 5, 4, 0, 1, 0, 1, 0, 0, 0, 0, 'rare', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Bestia Apocalittica', 4, 'RG', 4, 5, 0, 1, 0, 1, 0, 0, 0, 0, 'rare', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re della Bestia Selvaggia', 5, 'RG', 5, 5, 0, 1, 0, 1, 0, 0, 0, 0, 'rare', 'Beast', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sovrano Selvaggio Primordiale', 6, 'RG', 6, 6, 0, 1, 0, 1, 0, 0, 0, 0, 'mythic', 'Beast', '', 1, 'custom');
