-- Bicolore RW: Soldati Particolari
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato Benedetto', 2, 'RW', 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 'common', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato del Varco', 2, 'RW', 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato Consacrato', 2, 'RW', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Guerriero Sacro', 3, 'RW', 2, 2, 0, 1, 0, 0, 0, 1, 0, 0, 'uncommon', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato Fiammeggiante', 3, 'RW', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Paladino della Luce', 3, 'RW', 2, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Campione della Fede', 3, 'RW', 3, 3, 0, 1, 0, 0, 0, 1, 0, 0, 'rare', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato Glorioso', 4, 'RW', 3, 3, 0, 1, 0, 0, 0, 1, 0, 0, 'uncommon', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Soldato Immortale', 4, 'RW', 4, 4, 0, 1, 0, 0, 0, 1, 0, 0, 'rare', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Guerriero della Resurrezione', 4, 'RW', 4, 3, 0, 1, 0, 0, 0, 1, 0, 0, 'rare', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Generale Consacrato', 5, 'RW', 5, 4, 0, 1, 0, 0, 0, 1, 0, 0, 'rare', 'Soldier', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Arcipaladino della Luce Eterna', 6, 'RW', 6, 5, 0, 1, 0, 0, 0, 1, 0, 0, 'mythic', 'Soldier', '', 1, 'custom');
