-- Bicolore UB: Furfanti
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Astuto', 2, 'UB', 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante del Varco', 2, 'UB', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Ingannevole', 2, 'UB', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Assassino', 3, 'UB', 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Subdolo', 3, 'UB', 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Malvagio', 3, 'UB', 2, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Furfanti', 3, 'UB', 3, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Ombra', 4, 'UB', 3, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'uncommon', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante Spettrale', 4, 'UB', 4, 3, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Furfante del Buio', 4, 'UB', 3, 4, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Furfanti', 5, 'UB', 5, 4, 0, 0, 1, 0, 0, 0, 0, 0, 'rare', 'Rogue', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Maestro dell''Inganno Eterno', 6, 'UB', 5, 5, 0, 0, 1, 0, 0, 0, 0, 0, 'mythic', 'Rogue', '', 1, 'custom');
