-- Bicolore UR: Demoni delle Saette
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone Scintillante', 2, 'UR', 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'common', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone del Varco Fulminante', 2, 'UR', 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 'common', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Fulmine Demoniaco', 2, 'UR', 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone della Tempesta', 3, 'UR', 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 'uncommon', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone Fulmine', 3, 'UR', 2, 3, 1, 0, 0, 0, 0, 0, 0, 0, 'common', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone Saettatore', 3, 'UR', 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore dei Demoni Fulminanti', 3, 'UR', 3, 3, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone della Saetta Cosmica', 4, 'UR', 4, 3, 1, 1, 0, 0, 0, 0, 0, 0, 'uncommon', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone Tempesta Elettrica', 4, 'UR', 4, 4, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Demone della Furia Fulminante', 4, 'UR', 5, 4, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re dei Demoni Fulminanti', 5, 'UR', 5, 5, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Demon', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Principe della Tempesta Demoniaca', 6, 'UR', 6, 5, 1, 1, 0, 0, 0, 0, 0, 0, 'mythic', 'Demon', '', 1, 'custom');
