-- Bicolore WB: Chierici
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico della Fede', 2, 'WB', 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico del Varco', 2, 'WB', 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sacerdote Benedetto', 2, 'WB', 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Guaritore', 3, 'WB', 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Combattente', 3, 'WB', 2, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'common', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Mistico', 3, 'WB', 3, 2, 0, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sommo Sacerdote', 3, 'WB', 2, 3, 0, 0, 1, 0, 0, 1, 0, 0, 'rare', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Glorioso', 4, 'WB', 3, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Immortale', 4, 'WB', 4, 3, 0, 0, 0, 0, 0, 1, 0, 0, 'rare', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Chierico Redentore', 4, 'WB', 3, 4, 0, 0, 0, 0, 0, 1, 0, 0, 'rare', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Patriarca Sacro', 5, 'WB', 4, 4, 0, 0, 0, 0, 0, 1, 0, 0, 'rare', 'Cleric', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sommo Chierico Eterno', 6, 'WB', 5, 5, 0, 0, 0, 0, 0, 1, 0, 0, 'mythic', 'Cleric', '', 1, 'custom');
