-- Bicolore WU: Sphinx
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Custode', 2, 'WU', 1, 3, 1, 0, 0, 0, 0, 0, 0, 1, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge del Varco', 2, 'WU', 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Saggio', 2, 'WU', 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 'common', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Sapiente', 3, 'WU', 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Consigliata', 3, 'WU', 2, 3, 1, 0, 0, 0, 0, 1, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Guardiana', 3, 'WU', 1, 4, 1, 0, 0, 0, 0, 0, 1, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Signore degli Sphinx', 3, 'WU', 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Colossale', 4, 'WU', 4, 4, 1, 0, 0, 0, 0, 0, 0, 0, 'uncommon', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Primordiale', 4, 'WU', 4, 4, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Celeste', 4, 'WU', 3, 5, 1, 0, 0, 0, 0, 1, 1, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Re degli Sphinx', 5, 'WU', 5, 5, 1, 1, 0, 0, 0, 0, 0, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Sfinge Eternale', 6, 'WU', 5, 6, 1, 0, 0, 0, 0, 1, 1, 0, 'rare', 'Sphinx', '', 1, 'custom');
INSERT INTO magic_cards (id, name, mana_value, colors, power, toughness, flying, first_strike, deathtouch, trample, double_strike, lifelink, reach, defender, rarity, subtypes, image_url, enabled, source) VALUES (HEX(RANDOM_BYTES(16)), 'Patriarca Sphinx Immortale', 6, 'WU', 6, 6, 1, 1, 0, 0, 0, 1, 0, 0, 'mythic', 'Sphinx', '', 1, 'custom');
